### ISSUE TITLE
内部エラーが発生する操作パターンがある

### ISSUE THREAD

**Issue by fkd-tks** [haru-labo/SimpleJSTimer#1]
https://github.com/haru-labo/SimpleJSTimer/blob/ec23ff155e2346dafc180188cf740ad80e204dc3/js/timer.js#L79-L82

`TIMEUP`と表示するとき、`innerHTML`を書き換えてると思うんだけど、
その状態でここに来ると、`id='minute'`と`id='seconds'`の要素がなくエラーになってしまうので、例えば下記のようにnullチェックをしたほうがいいように思う。
（操作としては、TIMEUP→(リセットせずに)ストップボタン→スタートボタン）

```js
  let minElement = document.getElementById('minute');
  let secElement = document.getElementById('seconds');
  if (!minElement || !secElement) {
      clearInterval(countdownTimer);
      alert('リセットしてください!')
      return;
  }
```
（`+1Min`、`-1Min`、、、のクリック処理も同様。）
もっというと、`TIMEUP`の表示中はリセットボタン以外は`disabled`にするなどして、
そもそも要素がない状態でここに来ないようにするのがベター。

JavaScriptなのでエラーが起きても後続の処理が中断されるだけで、
今回の場合だと問題はないのだけど、基本的にはエラーにならないようにすべきかな。
わざとエラーにして中断させる実装もありえなくはないかもしれないけど、
その場合は他者が見たときにわかるよう意図的である旨のコメントを残すべき。

**Comment by haru-labo** [comment]
ご助言・ご指摘ありがとうございます。
今回はTimeUp時にすべてボタンをdisableにして対応しました。
-1secボタンの挙動も変更し、分が0より大きく秒が0の時に押下すると、分が‐1されるよう修正しました。

**Comment by fkd-tks** [comment]
プルリクエスト出す方法でやってみたんですね:thumbsup:
もうマージされちゃってましたが、#2 に指摘を書いてみました。

**Comment by fkd-tks** [comment]
ちょっと改善案をプルリクエストしてみました。#3

このIssueの内容自体は解決されてるのでもうクローズしますね
